### ISSUE TITLE
SaltConf15

### ISSUE THREAD

**Issue by mostafahussein** [whiteinge/presentations#1]
Hello,

I am looking for SaltConf15 pdf which is about "SaltStack Configuration Management Best Practices" , i couldn't find  it in here!

Thanks

**Comment by whiteinge** [comment]
Added [here](https://github.com/whiteinge/presentations/blob/master/saltconf_2015_configuration-management-best-practices/SaltStack%20Configuration%20Management%20Best%20Practices.pdf). Thanks for the bump. :-)
